services:
  n8n:
    build: .
    container_name: n8n
    environment:
      DB_SQLITE_POOL_SIZE: '2'
      N8N_RUNNERS_ENABLED: 'true'
      N8N_BLOCK_ENV_ACCESS_IN_NODE: 'false'
      N8N_GIT_NODE_DISABLE_BARE_REPOS: 'true'
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
    name: n8n_data
